### PR TITLE
CompassEx new feature

### PR DESCRIPTION
**Pull request by Mtihc**
Hi, 

You've already read it on dev.bukkit.org. This is the feature with saved private/public locations.

Glad you like it! I wanted a plugin to replace "warps". Your plugin was almost perfect for it. And now it is!
I'm happy you will add it to the official plugin :D

(PS: The version number is still 0.8.0, you might wanna update that?)

Greetings,
Mitch

### CODE REVIEW

**Comment by Philipp15b** [comment]
I'll add #5 and then the new version will be released. 0.9 or already 1.0?

**Comment by Mtihc** [comment]
Hm, I don't know. I will leave it up to you haha xD.... I think....
If you add-and-release #5 before you add-and-release my stuff... i think it should be 0.9 and 1.0.
But if you do it both at once... it should just be 0.9.

By the way... isn't that impossible? How do you know the bed location... the bed location IS the compass target right?

**Comment by Mtihc** [comment]
Oops... no it isnt. Sorry... i had a brainfart haha

**Comment by Philipp15b** [comment]
/compass spawn points to the world spawn, while /compass bed will point at the player's own spawn (where he slept). There is also a method called [getBedSpawnLocation](http://jd.bukkit.org/apidocs/org/bukkit/entity/Player.html#getBedSpawnLocation%28%29) which will exactly do that ;)

**Comment by Mtihc** [comment]
Yeah I know, it came to me a minute after i posted.
Haha dunno what i was thinking.

On Sat, Mar 10, 2012 at 8:51 PM, Philipp Schrer <
reply@reply.github.com

**Comment by Mtihc** [comment]
i think i should change the private/public system.

Because... when a player makes a location public... he can only make it private again if he has permission.
But if he has that permission... he can also make other public locations private. You know what i mean?

So maybe you should wait... so that there's not a big change AGAIN after the coming update.

**Comment by Philipp15b** [comment]
So players do have to OWN locations even if the locations are public, right? Maybe add owner information to the locations. Anyways, it'll be great if you update this and dont forget to work against the latest commit here ;)

**Comment by Mtihc** [comment]
Yes that is exactly it. The have to OWN public locations.

I went out of my way to make public locations have no owners. But now I realize thats not very handy.

Good thing you mentioned i have to work against the latest commit :)

**Comment by Philipp15b** [comment]
Maybe create a new class like 'NamedLocation' ([Source](https://github.com/sk89q/commandbook/blob/master/src/main/java/com/sk89q/commandbook/locations/NamedLocation.java)) like in CommandBook which also saves the owner. Then implement the serializable interface and it will be easily saved in the config. ([Wiki entry](http://wiki.bukkit.org/Introduction_to_the_New_Configuration#Serializing_and_Deserializing_Objects))

**Comment by Mtihc** [comment]
Good idea. I've done serialization a lot.

**Pull request merged**
